name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - pandas=2.2.1
  - pytest=8.0.2
  - scipy=1.12.0
  - pip=24.0
  - pip:
      - mlflow==2.10.2
      - wandb==0.16.0
